# Generated by Django 3.2.25 on 2024-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_voicerecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
